### ISSUE TITLE
Boost library not found error

### ISSUE THREAD

**Issue by pinklamp** [ToruNiina/afmize#10]
I am trying to install afmize but at the 'cmake ..' stage, I get the error below. It seems that the boost library cannot be downloaded from the link in CMakeLists.txt. I would appreciate your help! I am using Windows, with Cmake, git, and C++ compiler.

-- Boost library not found. Donwloading...

CMake Error at CMakeLists.txt:22 (file):
  file DOWNLOAD HASH mismatch
    for file: [C:/Users/S/afmize/extlib/boost_1_72_0.tar.gz]
      expected hash: [c66e88d5786f2ca4dbebb14e06b566fb642a1a6947ad8cc9091f9f445134143f]
        actual hash: [e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855]
             status: [22;"HTTP response code said error"]

CMake Error at CMakeLists.txt:31 (message):
  failed to download Boost library."HTTP response code said error"

**Comment by ToruNiina** [comment]
Hi,
I found that the boost library changes the download URL.
I updated the URL and also re-wrote CMakeLists.txt to search boost library in your system before downloading it.
I think now the problem is resolved. If you find it does not help, please reopen this.
