### ISSUE TITLE
makeしたときにでるエラー

### ISSUE THREAD

**Issue by ShinoGenki** [ToruNiina/afmize#3]
buildディレクトリを作成して移動し、cmakeは実行できましたが、
makeをしたら以下のコメントが出ました。

[ 12%] Building CXX object src/CMakeFiles/afmize.dir/afmize.cpp.o
/home/shino/afmize/src/afmize.cpp: In instantiation of ‘main(int, char**)::<lambda(auto:1)> [with auto:1 = afmize::system<double>]’:
/home/shino/afmize/src/afmize.cpp:355:60:   required from here
/home/shino/afmize/src/afmize.cpp:345:17: internal compiler error: Segmentation fault
                 if(stage_align) // align the lower edge of bounding box to stage
                 ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
src/CMakeFiles/afmize.dir/build.make:62: recipe for target 'src/CMakeFiles/afmize.dir/afmize.cpp.o' failed
make[2]: *** [src/CMakeFiles/afmize.dir/afmize.cpp.o] Error 1
CMakeFiles/Makefile2:96: recipe for target 'src/CMakeFiles/afmize.dir/all' failed
make[1]: *** [src/CMakeFiles/afmize.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2

解決策の検討をよろしくお願いいたします。

**Comment by ToruNiina** [comment]
エラーメッセージにある通り、コンパイラの内部エラーです。
[travis](https://www.travis-ci.com/ToruNiina/afmize)では`g++-7`と`clang-6.0`でテストしているので、それらと同じか、より新しいコンパイラを使用してください。
