### ISSUE TITLE
Height and position of scale bar

### ISSUE THREAD

**Issue by sotaro915** [ToruNiina/afmize#6]
Hi !
Now, the length of scale bar can be specified, but its height and position cannot.
When generating a high resolution image, I was faced with the problem that the scale bar was missing.
I'm so happy if the scale-bar height and position can be specified as well as its length can.
In addition, I'm glad if I can hide the scale bar when needed because the scale bar cannot be hidden completely by setting its length to be zero.   
 
Best,
Sotaro

**Comment by ToruNiina** [comment]
I implemented the following just now.
- make `scale_bar` optional in the input file.
- make the size and position of the scale bar relative to the image

By this, I think most of the problems you have will be resolved, I think.

**Comment by sotaro915** [comment]
Thanks a lot.
