### ISSUE TITLE
Rotation of initial PDB file structure.

### ISSUE THREAD

**Issue by k-haru** [ToruNiina/afmize#9]
Hi :)
I want to get an image of the rotated structure in AFMize.
Do you know how to rotate the coordinates? Or can you implement it? :)

**Comment by ToruNiina** [comment]
Hi,

You can rotate a molecule by multiplying a rotation matrix and the coordinates of molecules you want to rotate. It is better to move the center of mass of the molecule to the origin to avoid large movement.

There should be a lot of libraries to read and write a pdb files and operate molecular coordinates, such as [chemfiles](https://chemfiles.org/) and [MDAnalysis](https://docs.mdanalysis.org/1.0.0/_modules/MDAnalysis/transformations/rotate.html). I have [my own](https://github.com/ToruNiina/Coffee-mill) set of tools.

**Comment by k-haru** [comment]
Thanks for the advice!
